import os

IMAGE_SIZE = (800, 800)
PER_DISH_LIMIT = 3
SEARCH_CANDIDATE_LIMIT = 12
MIN_SOURCE_EDGE = 400
REQUEST_TIMEOUT = 15
REQUEST_RETRIES = 3
PIXABAY_API_KEY = os.getenv("PIXABAY_API_KEY", "")
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY", "")
